# Generated by Django 3.2.13 on 2022-04-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(default='', max_length=70)),
                ('author', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
